openapi: 3.0.3
info:
  title: Vinci Stock eXchange account service
  description: Microservice handling database of accounts in Vinci Stock eXchange
  version: 1.0.0
servers:
  - url: 'http://localhost:9000'
    description: Development server
paths:

  /accounts/{hash}:
    parameters:
      - name: hash
        in: path
        description: Hash of the account
        required: true
        schema:
          type: string
          example: dQw4w9WgXcQ

    post:
      summary: Create an account
      requestBody:
        description: Account to create
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/account'
      responses:
        400:
          description: Hash does not match or account invalid
        409:
          description: Account already exists
        201:
          description: Created account

    get:
      summary: Read an account and its total value
      responses:
        404:
          description: Account not found
        200:
          description: Returned account
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/account'

    put:
      summary: Update an account
      requestBody:
        description: New values of the account
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/account'
      responses:
        400:
          description: Hash does not match or account invalid
        404:
          description: Account not found
        200:
          description: Updated account

    delete:
      summary: Delete an account
      responses:
        404:
          description: Account not found
        200:
          description: Deleted account

components:
  schemas:
    account:
      type: object
      properties:
        hash:
          type: string
        user:
          type: integer
        cash:
          type: integer
          description: in euros
        securities:
          type: object
          additionalProperties: integer
      example:
        hash: dQw4w9WgXcQ
        userId: 4
        cash: 21404.32
        securities: {"Security A": 50, "Security B" : 10}