
### Read one
GET http://localhost:9001/investor/bob

### Create one
POST http://localhost:9001/investor/bob
Content-Type: application/json

{
  "investorData": {
    "username": "bob",
    "email": "bob@gmail.com",
    "firstname": "Bob",
    "lastname": "Eponge",
    "birthday": "2000-01-01"
  },
  "password": "Patrick"
}

### Update one
PUT http://localhost:9001/investor/bob
Content-Type: application/json

{
    "username": "bob",
    "email": "bob.eponge@gmail.com",
    "firstname": "Bob",
    "lastname": "Eponge",
    "birthday": "2000-01-01"
}