### Read price
GET http://localhost:9004/price/ABCD

### Read price of non existing ticker
GET http://localhost:9004/price/XJKA

### Update price
PATCH http://localhost:9004/price/ABCD
Content-Type: text/plain

14.4

### Update price to a negative one (should return 400)
PATCH http://localhost:9004/price/ABCD
Content-Type: text/plain

-8.3