### Test execution
POST http://localhost:9007/execute/AAPL/bob/test
Content-Type: application/json

{
  "ticker": "AAPL",
  "seller": "bob",
  "buyer": "test",
  "buy_order_guid": "5073c3b8-4ff0-4169-95cc-14ba61a5b4a6",
  "sell_order_guid": "4561c3b8-4ff0-7845-95cc-14ba61a5b4a6",
  "quantity": 10,
  "price": 100
}