### Create invalid investor
POST http://localhost:8080/investor/testGatewayInvestor
Content-Type: application/json

{
  "investorData": {
    "username": "test8",
    "email": "bob@gmail.com",
    "firstname": "Bob",
    "lastname": "Eponge",
    "birthday": "2000-01-01"
  },
  "password": "Patrick"
}

### Create investor
POST http://localhost:8080/investor/testGatewayInvestor
Content-Type: application/json

{
  "investorData": {
    "username": "testGatewayInvestor",
    "email": "bob@gmail.com",
    "firstname": "Bob",
    "lastname": "Eponge",
    "birthday": "2000-01-01"
  },
  "password": "Patrick"
}

### Create existing investor
POST http://localhost:8080/investor/testGatewayInvestor
Content-Type: application/json

{
  "investorData": {
    "username": "testGatewayInvestor",
    "email": "bob@gmail.com",
    "firstname": "Bob",
    "lastname": "Eponge",
    "birthday": "2000-01-01"
  },
  "password": "Patrick"
}

### Connect user
POST http://localhost:8080/authentication/connect
Content-Type: application/json

{
  "username": "testGatewayInvestor",
  "password": "Patrick"
}

> {%
  client.global.set("token", response.body)
%}

### Read their own information
GET http://localhost:8080/investor/testGatewayInvestor
Authorization: {{token}}

### Read information while not being connected
GET http://localhost:8080/investor/testGatewayInvestor
Authorization: ''

### Read another investor's information
GET http://localhost:8080/investor/test
Authorization: {{token}}

### Update their own information
PUT http://localhost:8080/investor/testGatewayInvestor
Content-Type: application/json

{
  "username": "testGatewayInvestor",
  "email": "bob.eponge@gmail.com",
  "firstname": "Boby",
  "lastname": "Eponge",
  "birthday": "2000-01-01"
}

### Update another investor's information
PUT http://localhost:8080/investor/test
Content-Type: application/json

{
  "username": "test",
  "email": "bob.eponge@gmail.com",
  "firstname": "Boby",
  "lastname": "Eponge",
  "birthday": "2000-01-01"
}

### Create investor to test delete
POST http://localhost:8080/investor/test11
Content-Type: application/json

{
  "investorData": {
    "username": "test11",
    "email": "bob@gmail.com",
    "firstname": "Bob",
    "lastname": "Eponge",
    "birthday": "2000-01-01"
  },
  "password": "Patrick"
}

### Delete an investor
DELETE http://localhost:8080/investor/test11

### Delete non existing investor
DELETE http://localhost:8080/investor/test220

### Add cash to testGatewayInvestor wallet
POST http://localhost:8080/wallet/testGatewayInvestor/cash
Authorization: {{token}}
Content-Type: application/json

{
  "cash": 100.0
}

### Read Net worth value of testGatewayInvestor wallet
GET http://localhost:8080/wallet/testGatewayInvestor/net-worth
Authorization: {{token}}

### Delete an investor but the investor's situation does not allow (wallet not empty)
DELETE http://localhost:9001/investor/testGatewayInvestor

### Update Credentials
PUT http://localhost:8080/authentication/testGatewayInvestor
Authorization: {{token}}
Content-Type: application/json

{
  "username": "testGatewayInvestor",
  "password": "Patrick2"
}

### Create investor to test update bad requests
POST http://localhost:8080/investor/test9
Content-Type: application/json

{
  "investorData": {
    "username": "test9",
    "email": "bob@gmail.com",
    "firstname": "Bob",
    "lastname": "Eponge",
    "birthday": "2000-01-01"
  },
  "password": "Patrick"
}

### Update invest test9 credentials while being connected as testGatewayInvestor
PUT http://localhost:8080/authentication/test9
Authorization: {{token}}
Content-Type: application/json

{
  "username": "test9",
  "password": "Patrick2"
}

### Update invest testGatewayInvestor credentials with no valid token
PUT http://localhost:8080/authentication/test9
Authorization: ""
Content-Type: application/json

{
  "username": "test9",
  "password": "Patrick2"
}

### Create order
POST http://localhost:8080/investor/testGatewayInvestor
Content-Type: application/json

{
  "owner": "testGatewayInvestor",
  "timestamp": 123446599789,
  "ticker": "AAPL",
  "quantity": 10,
  "side": "BUY",
  "type": "LIMIT",
  "limit": 100.0,
  "filled": 0
}

### Read all my orders
GET http://localhost:8080/order/by-user/testGatewayInvestor
Authorization: {{token}}

### Read all orders of another investor while being connected as testGatewayInvestor
GET http://localhost:8080/order/by-user/test9
Authorization: {{token}}

### Read all open positions of an investor
GET http://localhost:8080/wallet/testGatewayInvestor
Authorization: {{token}}

### Read all open positions of another investor while being connected as testGatewayInvestor
GET http://localhost:8080/wallet/test9
Authorization: {{token}}

### Read all open positions of another investor while being connected as testGatewayInvestor
GET http://localhost:8080/wallet/test9
Authorization: {{token}}

### Add 10 quantity of the ticker 'XYZ' in testGatewayInvestor
POST http://localhost:8080/wallet/testGatewayInvestor/position/XYZ
Authorization: {{token}}
Content-Type: application/json

{
  "quantity": 10.0
}

### Read price of XYZ
GET http://localhost:8080/price/XYZ




