### Connect user
POST http://localhost:8080/authentication/connect
Content-Type: application/json

{
  "username": "test",
  "password": "blablabla"
}

> {% client.global.set("token", response.body) %}


### Read investor
GET http://localhost:8080/investor/bob
Authorization: {{token}}

### Create investor
POST http://localhost:8080/investor/david
Content-Type: application/json

{
  "investorData": {
    "username": "david",
    "email": "bob@gmail.com",
    "firstname": "Bob",
    "lastname": "Eponge",
    "birthday": "2000-01-01"
  },
  "password": "Patrick"
}

